### ISSUE TITLE
Alt tags for project images are not descriptive

### ISSUE THREAD

**Issue by manniL** [hcarneiro/thegeekdeveloper-portfolio#12]
**Describe the bug**

The alternative tags won't help ppl that rely on them.

![image](https://user-images.githubusercontent.com/640208/59384423-6ad27680-8d62-11e9-86ef-6b2e6ed21971.png)

**To Reproduce**
1. Access the website
2. Check an alt tag of a project image

**PS**: Also an ~~pointer cursor~~ actual link instead of a div would be nice for semantic HTML :relaxed: -> Remove           `tag="div"` from https://github.com/hcarneiro/thegeekdeveloper-portfolio/blob/master/pages/work/index.vue#L36

**Comment by hcarneiro** [comment]
Issue fixed and released!

**Comment by hcarneiro** [comment]
@manniL yeah you are right. Sorry, focused only on the `alt` attributes.
Reopening!

**Comment by hcarneiro** [comment]
Issue is now fixed. Links are actual links now.
